
add_newline = true
command_timeout = 400
# format = '$all$directory$character'
# A minimal left prompt
# move the rest of the prompt to the right

[character]
success_symbol = "[îœ î‰ ](fg:#7dcfff)"
error_symbol = "[îœ î‰ ](fg:#F05954)"
vicmd_symbol = "[î˜« î‰](purple)"
format = ' $symbol'

[git_state]
disabled = false

[git_status]
format = '([$all_status]($style))'
conflicted = "([âš ï¸ ${count}](bold red) )"
ahead = "([âŸ«${count}])"
behind = "([âŸª${count}])"
# stashed = "([ïŒ¹ ${count}](bold red)) "
stashed = "([ï‰• ${count}](bold red)) "
modified = "([ï‘™ ${count}](bold yellow) )"
staged = "([ïƒ¾ ${count}](bold green) )"
renamed = "([â‡† ${count}](vold blue) )"
deleted = "([ï…† ${count}](bold red) )"
untracked = "([ï™ ${count}](dimmed red) )"


# -----------------
#     BATTERY
# -----------------
[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = 'ğŸ’¦'

[cmd_duration]
disabled = true

# -----------------
#     KUBERNETES
# -----------------
[kubernetes]
format = 'k8 [$symbol  ($context )]($style)'
disabled = false
# detect_files = ['value.yaml', 'Chart.yaml']
contexts = [
]

[git_branch]
symbol = 'ó°˜¬ '
truncation_length = 25

[nodejs]
symbol = 'î´ '

[nats]
disabled = false

[aws]
disabled = false
symbol = 'ó°…Ÿ '
expiration_symbol = 'ó°…¤ '

[aws.region_aliases]
eu-west-1 = 'ew1'
eu-north-1 = 'en1'

[azure]
disabled = true
# -----------------
#     Helm
# -----------------
[helm]
disabled = true

# -----------------
#     Package
# -----------------
[package]
disabled = true

# -----------------
#     Time
# -----------------
[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+2'
time_range = '14:30:00-18:00:00'

[directory]
read_only = ' ó°Œ¾'
truncation_symbol = '.../'
truncate_to_repo = false
truncation_length = 3
