
add_newline = true
command_timeout = 400
# format = '$all$directory$character'
# A minimal left prompt
# move the rest of the prompt to the right

[character]
success_symbol = "[îœ î‰ ](fg:#7dcfff)"
error_symbol = "[îœ î‰ ](fg:#F05954)"
vicmd_symbol = "[î˜« î‰](purple)"
format = ' $symbol'

[git_state]
disabled = false

[git_status]
format = '([$all_status]($style))'
conflicted = "([âš ï¸ ${count}](bold red) )"
ahead = "([âŸ«${count}])"
behind = "([âŸª${count}])"
# stashed = "([ïŒ¹ ${count}](bold red)) "
stashed = "([ï‰• ${count}](bold red)) "
modified = "([ï‘™ ${count}](bold yellow) )"
staged = "([ïƒ¾ ${count}](bold green) )"
renamed = "([â‡† ${count}](vold blue) )"
deleted = "([ï…† ${count}](bold red) )"
untracked = "([ï™ ${count}](dimmed red) )"


# -----------------
#     BATTERY
# -----------------
[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
discharging_symbol = 'ğŸ’¦'

[cmd_duration]
disabled = true

# -----------------
#     KUBERNETES
# -----------------
[kubernetes]
format = 'k8 [$symbol  ($context )]($style)'
disabled = false
# detect_files = ['value.yaml', 'Chart.yaml']
contexts = [
  { context_pattern = "tardis-k8s-sand.*", context_alias = "ta-sbox", symbol = 'ğŸ–', style = 'bold green' },
  { context_pattern = "tardis-k8s-dev.*", context_alias =  "ta-dev", symbol = 'ğŸš§', style = 'bold blue' },
  { context_pattern = "tardis-k8s-stag.*", context_alias = "ta-stage", symbol = 'ğŸš¦', style = 'bold yellow' },
  { context_pattern = "tardis-k8s-prod.*", context_alias = "ta-prod", symbol = 'ğŸš€', style = 'bold red' },
  { context_pattern = "tardis-k8s-sink.*", context_alias = "ta-sink", symbol = 'ğŸš½', style = 'bold orange' },
]

[git_branch]
symbol = 'ó°˜¬ '
truncation_length = 25

[nodejs]
symbol = 'î´ '

[nats]
disabled = false

[aws]
disabled = false
symbol = 'ó°…Ÿ '
expiration_symbol = 'ó°…¤ '

[aws.region_aliases]
eu-west-1 = 'ew1'
eu-north-1 = 'en1'

[azure]
disabled = true
# -----------------
#     Helm
# -----------------
[helm]
disabled = true

# -----------------
#     Package
# -----------------
[package]
disabled = true

# -----------------
#     Time
# -----------------
[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = '+2'
time_range = '14:30:00-18:00:00'

[custom.vault]
command = 'echo ${VAULT_ADDR} | sed -n "s/.*\(enigma\)\(\.dev\|\.stage\)*\(.*\)/\1\2/p"'
description = 'show Vault server'
when = ''' [[ -n ${VAULT_ADDR} ]] && [[ -n ${VAULT_TOKEN} ]] '''
format = '[$symbol($output)]($style)'
disabled = false
os = 'linux'
symbol = 'ó°¥ '

[directory]
read_only = ' ó°Œ¾'
truncation_symbol = '.../'
truncate_to_repo = false
truncation_length = 3

[directory.substitutions]
"~/plejd/cloudops/iac" = "@iac"
"~/plejd/cloudops/kubernetes/applications-state" = "@as"
"~/plejd/cloudops/plejd_shell" = "@pshell"
"~/plejd/cloudops/nats/nats-accounts" = "@nats"

